// <auto-generated />
namespace WebVize.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "202211221546105_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAN1YzY7bNhC+F+g7CDqlh4jOFgiShZxgY+8WRuvdReRujwUtjW2iJKWS1MbOq+XQR+ordGj9Wj9eeTc/SC+GRc5883FmODPSv5/+8d9uBXfuQWkWy7H7whu5Dsgwjphcj93UrJ6/ct+++fEH/zISW+eukDuzcqgp9djdGJOcE6LDDQiqPcFCFet4ZbwwFoRGMTkbjV6RFyMCCOEiluP471NpmID9Az5OYhlCYlLK53EEXOfruBPsUZ1rKkAnNISx+wcs79hH8DJJ7xKBzM51LjijSCYAvjqR2ei1ZeaWNtFqBrrYJbC3PHan6S5VKaeqLoaCv8LuYAGXblWcgDK797A6UJ5NXYccapOmeqnc0rRcxu5Mmp/PXOc65ZwuOS6sKNfgOsnL88DECn4BCYoaiG6pMaAwULMIcgftfXKevBzmltdkdGbdQqiUsaEGo96i30n2HdWcrVnBODAKM8l1rtgWot9Ars2mZD2n22IF/7rO75Jh4qGSUSnUT5k9D7H+jcwuqGKbwvYUA7DA5O6IUx3LJ1WWHc29i0gwyeFRqbfXnUWnZ16p+B0knv396oG/pVp/iFX0hQ0fzxKsm4YydH1OCoGnS7sIW9NIl0whANOsaH+6TmUiK6BeVe6aXmjCFMnZhVImbueJSu5VsSdZtS+6AulpC/6cJgk6u9Ym8hUnyHrE5HlwehMQGQYJdUcvKNmWljDt6Roau2gamV4xpQ2WAbqkNvyTSLTEhkSqMNUKWPPeV54vVOz/TK2zXXo9/azuyys8nsA7vD8plKR6e2GuHYQUt3r72CTmqZDH++LDSGWTacOVW6didoGdjpJ3gjZUvtHG80nD4c3oklZ4G7W8mTCD0qm6uE/Ppu4ONSiZ+lX7/Fx2prqPe/rcMZysa9RBspXhCFULqKNUq1851q3C2hQprZcFtlFI/byoPTyEt6pcJuI66KJ7FtkKF+y0AeFZAS/4m084w/NWAnMq2Qq0WcR/gX2hwCL8+CG+HBq0jvh3Mckz64sHR6ejA+TACVzeUxVuqHom6Panp03VnwHqYFKO8NjmfzYpf5HA1ifcJwWhObWeAHbaJNoegwaOo8en0azMYOYsYzxCRrXc1oOn1aPDapeNYlc/epZtl1af1L+C+FPQbF1B2G8iEkL7/lOBFjIzuYqLyOLp6owKkUbg52AoXjd6oQxb0dDgdgha719Z7ihPUeRSLCGayZvUJKm50BrEku/q5/XJcfv7gf2Qs3+T2Cf9OY6ANJmtGDfyXcp4VPK+6qgYPRA2K/NriazwlQ3h1rsS6TqWA4Fy900hAWkv9QJEwhFM38iA3kM/t4d9eOgxf8roWlFR92C2kjMJKFqumUADdY3Knv2IR+xXvDf/AS+RLkr3EwAA"; }
        }
    }
}
